
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async changeBinding(id: string, binding: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_binding", { id, binding }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetBinding(id: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeShortcutActivationSetting(activation: ShortcutActivation) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_shortcut_activation_setting", { activation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeHoldThresholdMsSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_hold_threshold_ms_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackVolumeSetting(volume: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_volume_setting", { volume }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSoundThemeSetting(theme: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_sound_theme_setting", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeThemeSetting(theme: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_theme_setting", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeStartHiddenSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_start_hidden_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutostartSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_autostart_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranslateToEnglishSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_translate_to_english_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSelectedLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_selected_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOverlayPositionSetting(position: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_overlay_position_setting", { position }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOverlayStyleSetting(style: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_overlay_style_setting", { style }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeDebugModeSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_debug_mode_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWordCorrectionThresholdSetting(threshold: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_word_correction_threshold_setting", { threshold }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExtraRecordingBufferSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_extra_recording_buffer_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteDelayMsSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_delay_ms_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteDelayAfterMsSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_delay_after_ms_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeReliablePasteSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_reliable_paste_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteMethodSetting(method: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_method_setting", { method }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableTypingTools() : Promise<string[]> {
    return await TAURI_INVOKE("get_available_typing_tools");
},
async changeTypingToolSetting(tool: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_typing_tool_setting", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExternalScriptPathSetting(path: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_external_script_path_setting", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeClipboardHandlingSetting(handling: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_clipboard_handling_setting", { handling }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoSubmitSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoSubmitKeySetting(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_key_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExperimentalEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_experimental_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessBaseUrlSetting(providerId: string, baseUrl: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_base_url_setting", { providerId, baseUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessApiKeySetting(providerId: string, apiKey: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_api_key_setting", { providerId, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessModelSetting(providerId: string, model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_model_setting", { providerId, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessProvider(providerId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_provider", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLocalModelStatus() : Promise<LocalModelStatus> {
    return await TAURI_INVOKE("get_local_model_status");
},
/**
 * Install whatever is missing (Ollama, then `model`, by default the
 * selected one), then start the server if the local provider is selected.
 */
async installLocalModel(model: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_local_model", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listLocalModels() : Promise<LocalModelEntry[]> {
    return await TAURI_INVOKE("list_local_models");
},
/**
 * The model currently being installed, if any.
 */
async installingLocalModel() : Promise<string | null> {
    return await TAURI_INVOKE("installing_local_model");
},
/**
 * Remove an Ollama model (frees its disk space unless another model shares
 * the weights).
 */
async deleteLocalModel(model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_local_model", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchPostProcessModels(providerId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_post_process_models", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addPostProcessPrompt(name: string, prompt: string) : Promise<Result<LLMPrompt, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_post_process_prompt", { name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePostProcessPrompt(id: string, name: string, prompt: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_post_process_prompt", { id, name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePostProcessPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_post_process_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessSelectedPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_selected_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCustomWords(words: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_custom_words", { words }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async teachStartRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("teach_start_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async teachStopRecording(word: string, whispered: boolean) : Promise<Result<TeachTake, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("teach_stop_recording", { word, whispered }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async teachCancelRecording() : Promise<void> {
    await TAURI_INVOKE("teach_cancel_recording");
},
/**
 * Delete clips of an abandoned teaching session.
 */
async teachDiscardClips(files: string[]) : Promise<void> {
    await TAURI_INVOKE("teach_discard_clips", { files });
},
/**
 * Save a teaching session for the current model, replacing any earlier one
 * for the same word (its old clips are deleted).
 */
async teachSaveWord(word: string, clips: TeachClip[], heard: string[], variants: string[], excluded: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("teach_save_word", { word, clips, heard, variants, excluded }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async teachDeleteWord(word: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("teach_delete_word", { word }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Change which mishearings of a word are rewritten for the current model.
 */
async teachSetExcluded(word: string, excluded: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("teach_set_excluded", { word, excluded }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-run saved clips on the current model. `force` recomputes words that
 * already have results for it; otherwise only missing ones are computed.
 */
async teachRecheck(force: boolean) : Promise<void> {
    await TAURI_INVOKE("teach_recheck", { force });
},
async changeInputGainSetting(gainDb: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_input_gain_setting", { gainDb }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoGainSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_gain_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeBenchmarkRecordingSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_benchmark_recording_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async benchmarkSummary() : Promise<BenchmarkSummary> {
    return await TAURI_INVOKE("benchmark_summary");
},
async openBenchmarkFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_benchmark_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Recorded dictations, newest first.
 */
async benchmarkRecords(offset: number, limit: number) : Promise<BenchmarkItem[]> {
    return await TAURI_INVOKE("benchmark_records", { offset, limit });
},
/**
 * Save (or, with an empty text, clear) what was actually said.
 */
async setBenchmarkGroundTruth(id: string, text: string) : Promise<Result<BenchmarkRecord, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_benchmark_ground_truth", { id, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Ask for a best guess at what was said: transcribe the raw audio with the
 * cloud speech models that have an API key, then have ChatGPT reconcile
 * those with the live transcript, what was pasted and your edits.
 */
async guessBenchmarkGroundTruth(id: string) : Promise<Result<BenchmarkRecord, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("guess_benchmark_ground_truth", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeVoiceControlEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_voice_control_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeContextAwarePasteSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_context_aware_paste_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeScreenContextSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_screen_context_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeScreenContextOnlineSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_screen_context_online_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeFocusMessageBoxSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_focus_message_box_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Where dictation is transcribed: "local" or a cloud provider ("openai",
 * "groq"). Switching to the cloud frees the local model's memory.
 */
async changeTranscriptionProviderSetting(provider: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_transcription_provider_setting", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async rulesFilePath() : Promise<string | null> {
    return await TAURI_INVOKE("rules_file_path");
},
async openRulesFile() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_rules_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Ask a remote model for the rules change that fixes `report`, given the
 * last few dictations. Nothing is saved until `save_rules`.
 */
async proposeRules(report: string) : Promise<Result<Proposal, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("propose_rules", { report }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save a new rules file; it's used from the next dictation.
 */
async saveRules(rules: string, reportId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_rules", { rules, reportId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Go back to the rules file from before the last change.
 */
async undoRules() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("undo_rules") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What the rules file holds, for the Vocabulary page.
 */
async learnedRules() : Promise<Learned> {
    return await TAURI_INVOKE("learned_rules");
},
/**
 * Remove one learned entry: `kind` is "word", "correction" or "soundalike".
 */
async forgetRule(kind: string, index: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("forget_rule", { kind, index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Past mistake reports, newest first.
 */
async mistakeReports() : Promise<Report[]> {
    return await TAURI_INVOKE("mistake_reports");
},
/**
 * Delete a report and its audio (the rules it added stay).
 */
async forgetMistakeReport(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("forget_mistake_report", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeResultPopupEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_result_popup_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeLocalModelKeepLoadedSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_local_model_keep_loaded_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeResultPopupSecondsSetting(seconds: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_result_popup_seconds_setting", { seconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAssistantEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_assistant_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAssistantNameSetting(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_assistant_name_setting", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAssistantModelSetting(model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_assistant_model_setting", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAssistantEffortSetting(effort: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_assistant_effort_setting", { effort }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAssistantNotesSetting(notes: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_assistant_notes_setting", { notes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAgentActionsSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_agent_actions_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startMeeting(mode: MeetingMode) : Promise<Result<MeetingInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_meeting", { mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopMeeting() : Promise<Result<MeetingInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_meeting") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMeetingState() : Promise<MeetingState> {
    return await TAURI_INVOKE("get_meeting_state");
},
async listMeetings() : Promise<MeetingInfo[]> {
    return await TAURI_INVOKE("list_meetings");
},
async openMeetingFolder(id: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_meeting_folder", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Path of one of a meeting's tracks, for playback.
 */
async meetingTrackPath(id: string, file: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("meeting_track_path", { id, file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The transcript so far, or `None` if there isn't one yet.
 */
async getMeetingTranscript(id: string) : Promise<Result<MeetingTranscript | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_meeting_transcript", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Transcribe a meeting that failed or was recorded before transcription.
 */
async transcribeMeeting(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcribe_meeting", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The user's notes on a meeting (Markdown), empty if none yet.
 */
async getMeetingNotes(id: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_meeting_notes", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save the user's notes; they're combined with the transcript when the
 * meeting is summarised.
 */
async saveMeetingNotes(id: string, notes: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_meeting_notes", { id, notes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameMeeting(id: string, title: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_meeting", { id, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The summary, if one has been written.
 */
async getMeetingSummary(id: string) : Promise<Result<Summary | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_meeting_summary", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write (or rewrite) the summary, with the notes as they are now.
 */
async summarizeMeeting(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("summarize_meeting", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The whole meeting as Markdown: summary, notes and transcript.
 */
async meetingMarkdown(id: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("meeting_markdown", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Name a voice in an in-person meeting ("Speaker 2" → "Sam").
 */
async renameMeetingSpeaker(id: string, speaker: number, name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_meeting_speaker", { id, speaker, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Transcribe a meeting again from scratch, with the engine chosen now (to
 * compare engines, or after changing vocabulary). The summary is rewritten
 * afterwards; the user's notes are kept.
 */
async retranscribeMeeting(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retranscribe_meeting", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMeetingSettings(update: MeetingSettingsUpdate) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_meeting_settings", { update }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What the summary is asked for when the user hasn't written their own.
 */
async defaultMeetingSummaryPrompt() : Promise<string> {
    return await TAURI_INVOKE("default_meeting_summary_prompt");
},
async changeAgentAutoSendSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_agent_auto_send_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resize the result popup to the card the overlay measured.
 */
async fitResultOverlay(height: number) : Promise<void> {
    await TAURI_INVOKE("fit_result_overlay", { height });
},
/**
 * Close the result popup (close button or countdown).
 */
async dismissResultOverlay() : Promise<void> {
    await TAURI_INVOKE("dismiss_result_overlay");
},
/**
 * Copy the popup's text so it can be pasted where it was meant to go.
 */
async copyResultText(text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_result_text", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Most recent dictations first.
 */
async getRecentDictations() : Promise<DictationRecord[]> {
    return await TAURI_INVOKE("get_recent_dictations");
},
async changeHistoryRetentionDaysSetting(days: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_history_retention_days_setting", { days }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeRecordingRetentionDaysSetting(days: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_recording_retention_days_setting", { days }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeCleanupLevelSetting(level: CleanupLevel) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_cleanup_level_setting", { level }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeCustomInstructionsSetting(text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_custom_instructions_setting", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeCategoryInstructionsSetting(instructions: CategoryInstructions) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_category_instructions_setting", { instructions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeCategoryStylesSetting(styles: CategoryStyles) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_category_styles_setting", { styles }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Replace the app/website → category assignments. Newly assigned entries
 * drop out of the "recently used" list.
 */
async updateAppRules(rules: AppRule[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_app_rules", { rules }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every installed app, known website, override and recently used app/site,
 * with its category — for the Style page.
 */
async listAppCategories() : Promise<CategorizedEntry[]> {
    return await TAURI_INVOKE("list_app_categories");
},
async clearRecentContexts() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_recent_contexts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppSwitchEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_app_switch_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppSwitchAnyInstalledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_app_switch_any_installed_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAppAliases(aliases: AppAlias[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_app_aliases", { aliases }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Apps the app switcher can target, for the alias picker.
 */
async listInstalledApps() : Promise<InstalledApp[]> {
    return await TAURI_INVOKE("list_installed_apps");
},
async updateVoiceTriggers(triggers: VoiceTrigger[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_voice_triggers", { triggers }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTextReplacements(replacements: TextReplacement[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_text_replacements", { replacements }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Temporarily unregister all bindings while the user is recording a
 * shortcut in the UI. This avoids firing actions while keys are recorded.
 */
async suspendAllBindings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suspend_all_bindings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-register all bindings after the user has finished recording.
 */
async resumeAllBindings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_all_bindings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMuteWhileRecordingSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_mute_while_recording_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppendTrailingSpaceSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_append_trailing_space_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeLazyStreamCloseSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_lazy_stream_close_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeVadEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_vad_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeVadBackendSetting(backend: VadBackend) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_vad_backend_setting", { backend }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeFillerWordRemovalEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_filler_word_removal_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_app_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeUpdateChecksSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_update_checks_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeShowWhatsNewOnUpdateSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_show_whats_new_on_update_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWhatsNewLastSeenVersionSetting(version: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_whats_new_last_seen_version_setting", { version }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Change the keyboard implementation with runtime switching.
 * This will unregister all shortcuts from the old implementation,
 * validate shortcuts for the new implementation (resetting invalid ones to defaults),
 * and register them with the new implementation.
 */
async changeKeyboardImplementationSetting(implementation: string) : Promise<Result<ImplementationChangeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_keyboard_implementation_setting", { implementation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current keyboard implementation
 */
async getKeyboardImplementation() : Promise<string> {
    return await TAURI_INVOKE("get_keyboard_implementation");
},
async changeShowTrayIconSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_show_tray_icon_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranscribeAcceleratorSetting(accelerator: TranscribeAcceleratorSetting) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_transcribe_accelerator_setting", { accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOrtAcceleratorSetting(accelerator: OrtAcceleratorSetting) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_ort_accelerator_setting", { accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranscribeGpuDevice(device: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_transcribe_gpu_device", { device }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return which accelerators and GPU devices are available for this build.
 * 
 * First-call cost is dominated by enumerating GPU devices through the
 * transcribe.cpp Metal/Vulkan backend, which loads dynamic libraries and
 * probes hardware. Run it on the blocking pool so the webview thread
 * stays responsive — see also the startup pre-warm in `lib.rs`.
 */
async getAvailableAccelerators() : Promise<AvailableAccelerators> {
    return await TAURI_INVOKE("get_available_accelerators");
},
/**
 * Start key recording mode
 */
async startHandyKeysRecording(bindingId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_handy_keys_recording", { bindingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop key recording mode
 */
async stopHandyKeysRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_handy_keys_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSecureInputStatus() : Promise<SecureInputStatus> {
    return await TAURI_INVOKE("get_secure_input_status");
},
async runKeyboardDiagnostic(durationSecs: number | null) : Promise<Result<KeyboardDiagnosticReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_keyboard_diagnostic", { durationSecs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async triggerUpdateCheck() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trigger_update_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showMainWindowCommand() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_main_window_command") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelOperation() : Promise<void> {
    await TAURI_INVOKE("cancel_operation");
},
async isPortable() : Promise<boolean> {
    return await TAURI_INVOKE("is_portable");
},
async isUpdateChecksLocked() : Promise<boolean> {
    return await TAURI_INVOKE("is_update_checks_locked");
},
async getAppDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLogDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setLogLevel(level: LogLevel) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_log_level", { level }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openRecordingsFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_recordings_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openLogDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openAppDataDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_app_data_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async thisMac() : Promise<ThisMac> {
    return await TAURI_INVOKE("this_mac");
},
/**
 * Check if Apple Intelligence is available on this device.
 * Called by the frontend when the user selects Apple Intelligence provider.
 */
async checkAppleIntelligenceAvailable() : Promise<boolean> {
    return await TAURI_INVOKE("check_apple_intelligence_available");
},
/**
 * Try to initialize Enigo (keyboard/mouse simulation).
 * On macOS, this will return an error if accessibility permissions are not granted.
 */
async initializeEnigo() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_enigo") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Initialize keyboard shortcuts.
 * On macOS, this should be called after accessibility permissions are granted.
 * This is idempotent - calling it multiple times is safe.
 */
async initializeShortcuts() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_shortcuts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sign in with ChatGPT in the browser. Returns the account email.
 */
async chatgptSignIn() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chatgpt_sign_in") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async chatgptSignOut() : Promise<void> {
    await TAURI_INVOKE("chatgpt_sign_out");
},
/**
 * The signed-in ChatGPT account's email, or `None` when signed out.
 */
async chatgptAccount() : Promise<string | null> {
    return await TAURI_INVOKE("chatgpt_account");
},
async getAvailableModels() : Promise<Result<ModelInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModelInfo(modelId: string) : Promise<Result<ModelInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_info", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelDownload(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_download", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCurrentModel() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_model") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTranscriptionModelStatus() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transcription_model_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isModelLoading() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_model_loading") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-scan local sources (custom models dir + shared HF cache) for models added
 * since launch
 */
async rescanLocalModels() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rescan_local_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateMicrophoneMode(alwaysOn: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_microphone_mode", { alwaysOn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMicrophoneMode() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_microphone_mode") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWindowsMicrophonePermissionStatus() : Promise<WindowsMicrophonePermissionStatus> {
    return await TAURI_INVOKE("get_windows_microphone_permission_status");
},
async openMicrophonePrivacySettings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_microphone_privacy_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableMicrophones() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_microphones") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the preferred-microphone priority list and reopen capture if needed.
 */
async updatePreferredMicrophones(names: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_preferred_microphones", { names }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableOutputDevices() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_output_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedOutputDevice(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_output_device", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedOutputDevice() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_output_device") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playTestSound(soundType: string) : Promise<void> {
    await TAURI_INVOKE("play_test_sound", { soundType });
},
async checkCustomSounds() : Promise<CustomSounds> {
    return await TAURI_INVOKE("check_custom_sounds");
},
async setClamshellMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_clamshell_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getClamshellMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_clamshell_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isRecording() : Promise<boolean> {
    return await TAURI_INVOKE("is_recording");
},
async getMicrophoneChannels(deviceName: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_microphone_channels", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedChannel(channel: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_channel", { channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setModelUnloadTimeout(timeout: ModelUnloadTimeout) : Promise<void> {
    await TAURI_INVOKE("set_model_unload_timeout", { timeout });
},
async getModelLoadStatus() : Promise<Result<ModelLoadStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_load_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unloadModelManually() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unload_model_manually") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistoryEntries(cursor: number | null, limit: number | null) : Promise<Result<PaginatedHistory, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history_entries", { cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleHistoryEntrySaved(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_history_entry_saved", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAudioFilePath(fileName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_audio_file_path", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteHistoryEntry(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_history_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async retryHistoryEntryTranscription(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_history_entry_transcription", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateHistoryLimit(limit: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_history_limit", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateRecordingRetentionPeriod(period: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_recording_retention_period", { period }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Checks if the Mac is a laptop by detecting battery presence
 * 
 * This uses pmset to check for battery information.
 * Returns true if a battery is detected (laptop), false otherwise (desktop)
 */
async isLaptop() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_laptop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
historyUpdatePayload: HistoryUpdatePayload,
streamPhaseEvent: StreamPhaseEvent,
streamTextEvent: StreamTextEvent
}>({
historyUpdatePayload: "history-update-payload",
streamPhaseEvent: "stream-phase-event",
streamTextEvent: "stream-text-event"
})

/** user-defined constants **/



/** user-defined types **/

export type ActionItem = { task: string; 
/**
 * Who does it, if said; empty otherwise.
 */
owner: string; 
/**
 * Where in the meeting it came up.
 */
at_ms: number | null }
/**
 * A spoken name for an app the app switcher can bring to the front
 * ("chat" → /Applications/Claude.app).
 */
export type AppAlias = { phrase: string; app_path: string }
/**
 * Destination category of the app or website being dictated into.
 */
export type AppCategory = "personal" | "work" | "email" | "other"
/**
 * Assigns an app or website to a category.
 */
export type AppRule = { kind: AppRuleKind; 
/**
 * Bundle identifier ("com.tinyspeck.slackmacgap") or domain ("slack.com").
 */
key: string; 
/**
 * Display name.
 */
label: string; category: AppCategory }
export type AppRuleKind = 
/**
 * Matched by bundle identifier.
 */
"app" | 
/**
 * Matched by website domain (and its subdomains) in a supported browser.
 */
"website"
/**
 * The container-level `serde(default)` (backed by the `Default` impl below)
 * guarantees every field — including ones added in the future — falls back to
 * its `get_default_settings()` value when missing from a stored settings
 * object, so a partial store can never fail the whole load (#1619).
 * Field-level defaults below take precedence where present.
 */
export type AppSettings = { 
/**
 * Internal settings schema marker for one-time migrations. Fresh installs
 * start at the current version; existing stores missing this key are
 * treated as version 0 and migrated forward.
 */
settings_schema_version?: number; 
/**
 * Defaults to empty on partial stores; the load path merges in the
 * default bindings for any missing keys before the settings are used.
 */
bindings?: Partial<{ [key in string]: ShortcutBinding }>; 
/**
 * Replaces the pre-0.10 `push_to_talk` bool; stores missing this key are
 * migrated from it in `apply_settings_migrations`.
 */
shortcut_activation?: ShortcutActivation; 
/**
 * Hold-or-toggle only: a press held at least this long is push-to-talk,
 * anything shorter is a tap that locks recording on.
 */
hold_threshold_ms?: number; audio_feedback?: boolean; audio_feedback_volume?: number; sound_theme?: SoundTheme; start_hidden?: boolean; autostart_enabled?: boolean; update_checks_enabled?: boolean; show_whats_new_on_update?: boolean; 
/**
 * The app version whose What's New the user has already seen. Fresh installs
 * default to the current version (nothing is "new" to them). Existing users
 * upgrading from before this key existed are blanked by the migration so they
 * see the current release's notes — see `apply_settings_migrations`.
 */
whats_new_last_seen_version?: string; selected_model?: string; onboarding_completed?: boolean; always_on_microphone?: boolean; selected_microphone?: string | null; 
/**
 * Microphones in priority order: the first one connected at recording
 * start is used, ahead of `selected_microphone`. Entries are kept while
 * disconnected.
 */
preferred_microphones?: string[]; 
/**
 * Which input channel to use on the selected microphone device.
 * None means "average all channels" (original behavior).
 */
selected_channel?: number | null; clamshell_microphone?: string | null; selected_output_device?: string | null; translate_to_english?: boolean; selected_language?: string; overlay_position?: OverlayPosition; debug_mode?: boolean; log_level?: LogLevel; 
/**
 * Where dictation is transcribed: "local" (the selected model on this
 * Mac) or a provider with a transcription API ("openai", "groq"),
 * using that provider's API key.
 */
transcription_provider?: string; custom_words?: string[]; model_unload_timeout?: ModelUnloadTimeout; word_correction_threshold?: number; 
/**
 * Legacy count limit (upstream); superseded by `history_retention_days`.
 */
history_limit?: number; 
/**
 * Days to keep dictation text in History (0 = forever). Starred entries
 * are always kept.
 */
history_retention_days?: number; 
/**
 * Days to keep the audio of each dictation (0 = never save audio).
 */
recording_retention_days?: number; 
/**
 * "Teach a word" sessions: saved clips (kept regardless of the retention
 * above) and, per transcription model, the mishearings to rewrite.
 */
taught_words?: TaughtWord[]; recording_retention_period?: RecordingRetentionPeriod; paste_method?: PasteMethod; clipboard_handling?: ClipboardHandling; auto_submit?: boolean; auto_submit_key?: AutoSubmitKey; post_process_enabled?: boolean; post_process_provider_id?: string; post_process_providers?: PostProcessProvider[]; post_process_api_keys?: SecretMap; post_process_models?: Partial<{ [key in string]: string }>; post_process_prompts?: LLMPrompt[]; post_process_selected_prompt_id?: string | null; mute_while_recording?: boolean; append_trailing_space?: boolean; 
/**
 * Adapt pasted text to the characters around the cursor (spacing,
 * mid-sentence casing), read via Accessibility.
 */
context_aware_paste?: boolean; 
/**
 * Give the cleanup model the text on screen around where the dictation
 * goes (the conversation above the text box, the draft), read via
 * Accessibility, so it spells names and terms as they appear.
 */
screen_context?: boolean; 
/**
 * Also send that screen text to online cleanup providers (otherwise
 * it's only used with the model on this Mac).
 */
screen_context_online?: boolean; 
/**
 * In Claude, Codex and WhatsApp, when no text box is focused, focus
 * the thread's message box before pasting.
 */
focus_message_box?: boolean; 
/**
 * When nothing can take the text (no text field focused), show it in
 * the overlay instead of pasting.
 */
result_popup_enabled?: boolean; 
/**
 * Seconds before that popup closes on its own; 0 keeps it until closed.
 */
result_popup_seconds?: number; 
/**
 * Keep the local cleanup model in memory. Off loads it when a
 * dictation starts and frees it when idle (less RAM, slower cleanups).
 */
local_model_keep_loaded?: boolean; 
/**
 * Saying the assistant's name anywhere in a dictation sends it, with the
 * text field's contents, to a ChatGPT model that writes the result.
 */
assistant_enabled?: boolean; assistant_name?: string; 
/**
 * The meeting mode last started (a call, or in person), used by the
 * shortcut and the tray.
 */
meeting_mode?: MeetingMode; 
/**
 * Which model cleans up and summarises meeting transcripts.
 */
meeting_llm?: MeetingLlm; 
/**
 * Tidy the transcript (fillers, false starts, punctuation) with the LLM.
 */
meeting_cleanup?: boolean; 
/**
 * Replaces the built-in guidance for how summaries are written; empty
 * uses the default.
 */
meeting_summary_prompt?: string; 
/**
 * Level quiet and distant voices in in-person recordings before
 * transcription. Separate from dictation's gain.
 */
meeting_auto_gain?: boolean; 
/**
 * Extra gain for the meeting mic track, in dB, before levelling.
 */
meeting_input_boost_db?: number; 
/**
 * Which engine transcribes meetings: the local model or a provider.
 */
meeting_transcriber?: MeetingTranscriber; 
/**
 * Tell speakers apart in in-person meetings.
 */
meeting_diarize?: boolean; 
/**
 * Let the assistant act on the computer (start Claude Code sessions, run
 * tasks in other apps), not just write into the field. Off by default.
 */
agent_actions_enabled?: boolean; 
/**
 * Send the prompt when Felix starts a Claude Code session, rather than
 * leaving it filled in.
 */
agent_auto_send?: boolean; assistant_model?: string; 
/**
 * Reasoning effort: "none", "low", "medium" or "high".
 */
assistant_effort?: string; 
/**
 * What the assistant should know about the user (name, email, address,
 * how they sign off), for filling in details.
 */
assistant_notes?: string; soundalikes?: Soundalike[]; app_language?: string; theme?: Theme; experimental_enabled?: boolean; lazy_stream_close?: boolean; keyboard_implementation?: KeyboardImplementation; show_tray_icon?: boolean; paste_delay_ms?: number; paste_delay_after_ms?: number; 
/**
 * Debug-gated ("beta") receipt-sequenced paste: restore the clipboard only
 * after the target app actually reads the transcript, instead of after a
 * fixed delay. See `paste_tx`. macOS and Windows only.
 */
reliable_paste?: boolean; typing_tool?: TypingTool; external_script_path?: string | null; filler_word_removal_enabled?: boolean; custom_filler_words?: string[] | null; transcribe_accelerator?: TranscribeAcceleratorSetting; ort_accelerator?: OrtAcceleratorSetting; 
/**
 * Stable transcribe.cpp device selector. This is derived from the backend's
 * `device_id` when available (or its name for backends such as Metal),
 * never from the process-local device registry index.
 */
transcribe_gpu_device?: string | null; extra_recording_buffer_ms?: number; vad_enabled?: boolean; 
/**
 * Experimental detector implementation. Silero remains the stable default.
 */
vad_backend?: VadBackend; 
/**
 * Which recording overlay to show: None / Minimal / Live. Streaming mode is
 * not gated on this — that follows model capability. Migrated from the old
 * `overlay_position` (position `none` → style `None`).
 */
overlay_style?: OverlayStyle; 
/**
 * Fixed pre-VAD input gain in dB (-20..=30).
 */
input_gain_db?: number; 
/**
 * Automatic gain control ahead of VAD for quiet speech and weak mics.
 */
auto_gain_enabled?: boolean; 
/**
 * For development: keep every dictation's audio before gain and VAD,
 * with what was transcribed, pasted and later edited, in `benchmark/`.
 */
benchmark_recording?: boolean; 
/**
 * Silero speech threshold per microphone name, overriding the default
 * (0.3). Lower keeps quieter speech: 0.1 suits a close clip-on mic
 * used for whispering.
 */
microphone_vad_thresholds?: Partial<{ [key in string]: number }>; 
/**
 * Voice Control mode: end-of-dictation key triggers, spoken
 * "new line" / "new paragraph", and the app switcher.
 */
voice_control_enabled?: boolean; voice_triggers?: VoiceTrigger[]; text_replacements?: TextReplacement[]; 
/**
 * "go to <app>" as a whole dictation brings that app to the front.
 */
app_switch_enabled?: boolean; 
/**
 * Also match any installed app by its name, not only `app_aliases`.
 */
app_switch_any_installed?: boolean; app_aliases?: AppAlias[]; 
/**
 * AI cleanup level for every dictation (needs Post Processing on).
 */
cleanup_level?: CleanupLevel; 
/**
 * The user's own instructions, one per line, added to the Clarity
 * prompt with priority over its rules (same single pass).
 */
custom_instructions?: string; 
/**
 * Extra instructions per destination category.
 */
category_instructions?: CategoryInstructions; 
/**
 * Formality per destination category.
 */
category_styles?: CategoryStyles; 
/**
 * User overrides of the automatic app/website → category assignment
 * (see `app_categories`).
 */
app_rules?: AppRule[]; 
/**
 * Recently dictated-into apps/sites without an assignment, newest first,
 * offered in the Style page for one-click assignment.
 */
recent_contexts?: AppRule[] }
export type AudioDevice = { index: string; name: string; is_default: boolean }
export type AutoSubmitKey = "enter" | "ctrl_enter" | "cmd_enter"
export type AvailableAccelerators = { transcribe: string[]; ort: string[]; gpu_devices: GpuDeviceOption[] }
export type BenchmarkItem = { record: BenchmarkRecord; 
/**
 * Absolute path of the raw audio, for playback.
 */
audio_path: string }
export type BenchmarkRecord = { id: string; at: string; 
/**
 * Raw audio file next to this record.
 */
audio: string; seconds: number; 
/**
 * Audio the speech model got after VAD (0 = VAD dropped everything).
 */
kept_seconds: number; gain_db: number; auto_gain: boolean; 
/**
 * What the AGC had learned when this recording started.
 */
gain_at_start: GainState; vad_backend: string; microphone: string | null; 
/**
 * Silero threshold override for this microphone (`None`: default 0.3).
 */
vad_threshold: number | null; language: string; app: string | null; bundle_id: string | null; 
/**
 * Speech model that produced `transcript`.
 */
model: string | null; 
/**
 * What the speech model heard, before rules and cleanup.
 */
transcript: string | null; error: string | null; 
/**
 * Exactly what was pasted.
 */
pasted: string | null; 
/**
 * The pasted text as it stood in the field after your edits.
 */
edited: string | null; 
/**
 * "unchanged", "edited", "rewritten" (too different to trust as ground
 * truth), or why the field couldn't be followed.
 */
edit: string | null; 
/**
 * What was actually said, typed or confirmed by you.
 */
ground_truth: string | null; 
/**
 * An OpenAI model's best guess at what was said, when asked for.
 */
guess: Guess | null; 
/**
 * The quiet-speech safety net, when it transcribed a second time.
 */
rescue: Rescue | null }
export type BenchmarkSummary = { dictations: number; edited: number; 
/**
 * Records with a ground truth from you.
 */
confirmed: number; guessed: number; megabytes: number }
export type BindingResponse = { success: boolean; binding: ShortcutBinding | null; error: string | null }
/**
 * An app or website with its automatic and effective category.
 */
export type CategorizedEntry = { kind: AppRuleKind; key: string; label: string; category: AppCategory; automatic: AppCategory; overridden: boolean; 
/**
 * Dictated into recently.
 */
recent: boolean }
/**
 * Custom instructions per destination category (one per line).
 */
export type CategoryInstructions = { personal: string; work: string; email: string; other: string }
export type CategoryStyles = { personal: Formality; work: Formality; email: Formality; other: Formality }
/**
 * How much the AI cleanup rewrites a dictation.
 */
export type CleanupLevel = 
/**
 * No AI cleanup: rules only.
 */
"none" | 
/**
 * Fillers, repeats, self-corrections, punctuation, numbers.
 */
"light" | 
/**
 * Light plus tightening for clarity and concision.
 */
"medium"
export type ClipboardHandling = "dont_modify" | "copy_to_clipboard"
export type CustomSounds = { start: boolean; stop: boolean }
export type DictationRecord = { id: number; timestamp_ms: number; app_name: string | null; bundle_id: string | null; url_host: string | null; 
/**
 * Exactly what was pasted (after context adaptation).
 */
pasted_text: string; first_word: string | null; last_word: string | null; at_start: FieldState | null; before_paste: FieldState | null; after_paste: FieldState | null; 
/**
 * `None` when the field couldn't be read or changed unexpectedly.
 */
inserted: InsertedSpan | null }
/**
 * A line of a before/after comparison.
 */
export type DiffLine = { 
/**
 * "same", "added" or "removed".
 */
kind: string; text: string }
export type EngineType = 
/**
 * Any GGML/GGUF model loaded through transcribe-cpp (Whisper, Parakeet,
 * Voxtral, Qwen3-ASR, Nemotron, …). The architecture is auto-detected from
 * the file, so this one variant covers the whole transcribe-cpp family.
 */
"TranscribeCpp" | "Parakeet" | "Moonshine" | "MoonshineStreaming" | "SenseVoice" | "GigaAM" | "Canary" | "Cohere"
export type FieldState = { role: string; text: string; selection: Selection | null }
/**
 * Capitalization/punctuation style applied per category.
 */
export type Formality = "formal" | "casual" | "very_casual"
/**
 * What the AGC has learned about the speaker and the room (linear RMS).
 */
export type GainState = { speech_level: number | null; noise_floor: number | null }
export type GpuDeviceOption = { id: string; name: string; total_vram_mb: number }
export type Guess = { 
/**
 * Word for word as spoken; only obvious mishearings corrected.
 */
text: string; confident: boolean; 
/**
 * Words the sources disagreed on.
 */
unsure: string[]; notes: string; 
/**
 * Model that wrote the guess.
 */
by: string; 
/**
 * The transcripts it was given.
 */
heard: Heard[]; at: string }
export type Heard = { by: string; text: string }
export type HistoryEntry = { id: number; file_name: string; timestamp: number; saved: boolean; title: string; transcription_text: string; post_processed_text: string | null; post_process_prompt: string | null; post_process_requested: boolean; 
/**
 * Whether this entry's audio is still on disk (retry and playback).
 */
has_audio: boolean; 
/**
 * The speech model that transcribed it (entries from before this was
 * kept have none).
 */
transcription_model: string | null }
export type HistoryUpdatePayload = { action: "added"; entry: HistoryEntry } | { action: "updated"; entry: HistoryEntry } | { action: "deleted"; id: number } | { action: "toggled"; id: number }
/**
 * Result of changing keyboard implementation
 */
export type ImplementationChangeResult = { success: boolean; 
/**
 * List of binding IDs that were reset to defaults due to incompatibility
 */
reset_bindings: string[] }
/**
 * Where the dictation landed in the field (UTF-16 offsets, as the
 * Accessibility API uses them).
 */
export type InsertedSpan = { start: number; length: number; text: string }
export type InstalledApp = { name: string; path: string; 
/**
 * CFBundleIdentifier, used to assign the app to a style category.
 */
bundle_id: string | null }
/**
 * Where a background step (the summary) has got to.
 */
export type JobStatus = "queued" | "running" | "done" | "failed"
export type KeyboardDiagnosticReport = { secure_input_enabled: boolean; culprit_pid: number | null; culprit_name: string | null; 
/**
 * Counts only — key identity is deliberately never captured.
 */
key_down: number; key_up: number; flags_changed: number; mouse: number; duration_ms: number }
export type KeyboardImplementation = "tauri" | "handy_keys"
export type LLMPrompt = { id: string; name: string; prompt: string }
/**
 * The rules file's entries, for the Vocabulary page.
 */
export type Learned = { words: string[]; corrections: TextReplacement[]; soundalikes: Soundalike[]; 
/**
 * The file has a mistake (the list is from the last good version).
 */
error: string | null }
export type LocalModelEntry = { 
/**
 * Ollama tag, e.g. `qwen3.5:4b`.
 */
id: string; installed: boolean; recommended: boolean; 
/**
 * The one that suits this Mac's memory and chip.
 */
recommended_for_device: boolean; 
/**
 * On-disk size when installed, else the approximate download size.
 */
size_mb: number }
export type LocalModelStatus = { 
/**
 * llama-server and the ollama CLI are available.
 */
runtime_installed: boolean; model: string; model_installed: boolean; installing: boolean }
export type LogLevel = "trace" | "debug" | "info" | "warn" | "error"
/**
 * A meeting's `meeting.json`.
 */
export type MeetingInfo = { id: string; mode: MeetingMode; status: MeetingStatus; 
/**
 * Unix milliseconds.
 */
started_at: number; ended_at: number | null; mic: string; 
/**
 * Why system audio wasn't recorded on a call.
 */
system_error: string | null; tracks: TrackSummary[]; 
/**
 * Set by the user; otherwise the page names it by mode and time.
 */
title?: string | null; 
/**
 * `None` for meetings recorded before transcription existed.
 */
transcript?: TranscriptStatus | null; transcript_error?: string | null; 
/**
 * The title came from the summary, so a new summary may replace it.
 */
title_is_auto?: boolean; 
/**
 * Summary and transcript cleanup.
 */
summary?: JobStatus | null; summary_error?: string | null; 
/**
 * Names the user gave to told-apart voices (in person), by number.
 */
speakers?: Partial<{ [key in number]: string }> }
/**
 * The model that tidies and summarises meeting transcripts.
 */
export type MeetingLlm = 
/**
 * Felix's model, with the ChatGPT sign-in.
 */
"chatgpt" | 
/**
 * The provider and model chosen for dictation cleanup.
 */
"cleanup"
export type MeetingMode = 
/**
 * Mic + system audio.
 */
"call" | 
/**
 * Mic only.
 */
"in_person"
/**
 * Meeting settings to change; fields left out stay as they are.
 */
export type MeetingSettingsUpdate = { llm: MeetingLlm | null; cleanup: boolean | null; summary_prompt: string | null; auto_gain: boolean | null; input_boost_db: number | null; transcriber: MeetingTranscriber | null; diarize: boolean | null }
/**
 * What the Meetings page shows about the current recording and transcription.
 */
export type MeetingState = { recording: MeetingInfo | null; elapsed_ms: number; transcribing: TranscribeProgress | null }
export type MeetingStatus = "recording" | "recorded" | 
/**
 * Handy quit or crashed while recording; the audio up to a few seconds
 * before is kept.
 */
"interrupted"
/**
 * What transcribes meetings.
 */
export type MeetingTranscriber = 
/**
 * The model selected for dictation, on this Mac.
 */
"local" | 
/**
 * OpenAI's transcription API, with the OpenAI key from cleanup providers.
 */
"openai" | 
/**
 * Groq's Whisper API, with the Groq key from cleanup providers.
 */
"groq"
/**
 * A meeting's transcript as the page shows it.
 */
export type MeetingTranscript = { 
/**
 * False while it's still being transcribed (what's there so far).
 */
complete: boolean; paragraphs: Paragraph[] }
export type ModelInfo = { id: string; name: string; description: string; filename: string; source: ModelSource; size_mb: number; is_downloaded: boolean; is_downloading: boolean; partial_size: number; is_directory: boolean; engine_type: EngineType; accuracy_score: number; speed_score: number; supports_translation: boolean; is_recommended: boolean; supported_languages: string[]; supports_language_selection: boolean; is_custom: boolean; supports_streaming: boolean; supports_language_detection: boolean }
export type ModelLoadStatus = { is_loaded: boolean; current_model: string | null }
/**
 * Where a model comes from and how Handy obtains it — the routing discriminant
 * for downloading and on-disk resolution.
 */
export type ModelSource = 
/**
 * Direct HTTP download from a URL (current blob.handy.computer hosting).
 */
{ Url: { url: string; 
/**
 * Expected SHA-256 for integrity verification; `None` skips it.
 */
sha256: string | null } } | 
/**
 * A file inside a Hugging Face Hub repo, fetched via hf-hub into the shared
 * HF cache (so other tools reuse it). The file within the repo is
 * [`ModelInfo::filename`].
 */
{ HuggingFace: { repo_id: string; revision: string } } | 
/**
 * Already present on disk — a user-provided custom model, or one discovered
 * in a shared cache. Nothing to download.
 */
"Local"
export type ModelUnloadTimeout = "never" | "immediately" | "min_2" | "min_5" | "min_10" | "min_15" | "hour_1" | "sec_15"
/**
 * What one transcription model made of a taught word's clips.
 */
export type ModelVariants = { model_id: string; 
/**
 * Transcript of each clip, in clip order.
 */
heard: string[]; 
/**
 * Normalized mishearings ("quinn") that get rewritten to the word.
 */
variants: string[]; 
/**
 * Mishearings the user chose not to rewrite (e.g. common words).
 */
excluded: string[] }
export type OrtAcceleratorSetting = "auto" | "cpu" | "cuda" | "directml" | "rocm"
export type OverlayPosition = "top" | "bottom"
/**
 * Which recording overlay to display. `Minimal` and `Live` share one base
 * (the pill); `Live` grows into the panel that shows live transcription text.
 * `None` hides the overlay entirely. Decoupled from whether the model runs in
 * streaming mode (that is driven purely by model capability).
 */
export type OverlayStyle = "none" | "minimal" | "live"
export type PaginatedHistory = { entries: HistoryEntry[]; has_more: boolean }
/**
 * A run of one speaker's segments, as shown on the page.
 */
export type Paragraph = { source: Source; start_ms: number; end_ms: number; 
/**
 * Cleaned up when cleanup ran, otherwise as transcribed.
 */
text: string; 
/**
 * As transcribed, when cleanup changed it.
 */
raw: string | null; 
/**
 * Which voice, when speakers were told apart.
 */
speaker: number | null }
export type PasteMethod = "ctrl_v" | "direct" | "none" | "shift_insert" | "ctrl_shift_v" | "external_script"
export type PermissionAccess = "allowed" | "denied" | "unknown"
export type PostProcessProvider = { id: string; label: string; base_url: string; allow_base_url_edit?: boolean; models_endpoint?: string | null; supports_structured_output?: boolean }
/**
 * A change to the rules file, suggested from the user's report.
 */
export type Proposal = { 
/**
 * The report's entry in `rule_reports.jsonl`.
 */
id: string; 
/**
 * What went wrong and what the change does, in plain words.
 */
explanation: string; 
/**
 * The fix needs a change to Handy itself, not only rules.
 */
needs_code_change: boolean; 
/**
 * The whole new file.
 */
rules: string; diff: DiffLine[]; tests: TestResult[]; 
/**
 * The new file doesn't parse.
 */
error: string | null }
export type RecordingRetentionPeriod = "never" | "preserve_limit" | "days_3" | "weeks_2" | "months_3"
/**
 * A mistake report, as kept in `REPORTS_FILE`.
 */
export type Report = { id: string; 
/**
 * RFC 3339.
 */
at: string; 
/**
 * "typed" or "voice".
 */
source: string; report: string; transcribed: string | null; pasted: string | null; transcription_model: string | null; has_audio: boolean; explanation: string; 
/**
 * Lines added or removed in the rules file ("+ …", "- …").
 */
change: string[]; 
/**
 * "applied", "proposed" (not applied), "no change" or "failed".
 */
status: string; error: string | null }
/**
 * A second transcription of audio a more sensitive silence threshold kept.
 */
export type Rescue = { threshold: number; kept_seconds: number; transcript: string | null; 
/**
 * Whether it replaced the first transcript.
 */
used: boolean }
export type SecretMap = Partial<{ [key in string]: string }>
export type SecureInputStatus = { 
/**
 * Secure input is currently enabled (live check)
 */
enabled: boolean; 
/**
 * Enabled continuously long enough to be considered stuck (not just a
 * password field gaining momentary focus)
 */
sustained: boolean; culprit_pid: number | null; culprit_name: string | null; 
/**
 * Carbon fallback registrations are currently active
 */
fallback_active: boolean; 
/**
 * Binding ids shadow-registered with identical semantics
 */
covered_bindings: string[]; 
/**
 * Side-specific binding ids widened to match either side while shadowed
 */
degraded_bindings: string[]; 
/**
 * Binding ids that cannot fire at all (e.g. fn+key, registration failure)
 */
uncovered_bindings: string[]; 
/**
 * The user tried to record a shortcut while secure input was active.
 * Treated as user impact even when every binding is covered, so the
 * warning banner appears and explains why recording refused.
 */
recorder_blocked: boolean }
export type Selection = { location: number; length: number }
/**
 * How the transcribe shortcut's key events drive a recording.
 */
export type ShortcutActivation = 
/**
 * Press to start, press again to stop.
 */
"toggle" | 
/**
 * Hold to record, release to stop.
 */
"push_to_talk" | 
/**
 * Hold to record and release to stop, or tap to keep recording until the
 * next press. Which one it was is decided by how long the key was held
 * (`hold_threshold_ms`).
 */
"hold_or_toggle"
export type ShortcutBinding = { id: string; name: string; description: string; default_binding: string; current_binding: string }
export type SoundTheme = "marimba" | "pop" | "custom"
/**
 * A name that gets transcribed as an ordinary word that sounds like it
 * ("Claude" as "cloud"). Each occurrence is checked against its sentence by
 * the local model, so the ordinary word still works.
 */
export type Soundalike = { 
/**
 * The ordinary word the transcription writes ("cloud").
 */
heard: string; 
/**
 * The name it may stand for ("Claude").
 */
word: string; 
/**
 * What the name is, for the model ("Anthropic's AI assistant").
 */
meaning: string; 
/**
 * Names that start with the word, in their own casing ("Claude Code").
 */
compounds?: string[]; 
/**
 * Words that, right before the heard word, make it the ordinary word
 * ("the cloud"). Empty: the built-in list (the, my, our…).
 */
ordinary_after?: string[]; 
/**
 * Apps (names or bundle ids) where the name is likely: there, even
 * "my cloud …" is checked instead of kept.
 */
name_in_apps?: string[]; 
/**
 * Likewise when the name is on screen where the dictation goes.
 */
name_if_on_screen?: boolean }
/**
 * Where a segment was heard.
 */
export type Source = 
/**
 * The user's mic: "Me" on a call.
 */
"mic" | 
/**
 * What the Mac played: "Them" on a call.
 */
"system"
/**
 * What the background work is doing.
 */
export type Stage = "transcribing" | "identifying" | "cleaning_up" | "summarizing"
/**
 * Phase of the streaming overlay card, emitted to drive its UI state.
 */
export type StreamPhase = 
/**
 * Receiving audio / live text (or waiting for the stream to begin). Rust
 * does not emit this today; the frontend starts in this phase and Rust only
 * emits transitions away from it.
 */
"listening" | 
/**
 * Finalizing or post-processing — show a spinner.
 */
"working"
/**
 * Emitted to switch the streaming overlay to a working spinner.
 */
export type StreamPhaseEvent = { phase: StreamPhase; 
/**
 * Present only when `phase` is `Working`.
 */
kind?: StreamWorkKind | null }
/**
 * Live transcription snapshot emitted to the overlay during a streaming run.
 * `committed` is the append-only, flicker-free prefix; `tentative` is the
 * volatile suffix the model may still rewrite.
 */
export type StreamTextEvent = { committed: string; tentative: string }
/**
 * Semantic kind of "working" phase, used to localize the spinner label.
 */
export type StreamWorkKind = "transcribing" | "polishing"
/**
 * `summary.json`.
 */
export type Summary = { title: string; overview: string; key_points: string[]; decisions: string[]; action_items: ActionItem[]; 
/**
 * Which model wrote it.
 */
model: string; 
/**
 * Unix milliseconds.
 */
generated_at: number }
export type TaughtWord = { word: string; clips: TeachClip[]; by_model: ModelVariants[] }
/**
 * One recorded take of a taught word.
 */
export type TeachClip = { 
/**
 * WAV file name in the vocab clips directory.
 */
file: string; whispered: boolean }
/**
 * Result of one teaching take.
 */
export type TeachTake = { 
/**
 * What the model transcribed (native biasing applied).
 */
heard: string; 
/**
 * After canonical vocabulary forms and correction rules.
 */
corrected: string; 
/**
 * Whether the corrected text already contains the word.
 */
recognized: boolean; 
/**
 * Normalized mis-hearing to offer as a rule ("quinn"), if any.
 */
variant: string | null; 
/**
 * The variant is an ordinary English word; a rule for it would rewrite
 * normal speech, so it is excluded by default.
 */
variant_is_common_word: boolean; 
/**
 * Saved clip for this take.
 */
clip: TeachClip }
/**
 * How a test case came out.
 */
export type TestResult = { said: string; expect: string; got: string; passed: boolean; 
/**
 * The local model decides this one; `got` is what it gives if it
 * agrees with the test.
 */
model_decides: boolean }
/**
 * Exact, case-insensitive whole-phrase substitution applied before cleanup,
 * for mis-hearings fuzzy custom-word matching can't reach
 * (e.g. "cube cuddle" → "kubectl").
 */
export type TextReplacement = { from: string; to: string }
/**
 * UI appearance mode. `System` follows the OS `prefers-color-scheme`; `Light`
 * and `Dark` force one of the two palettes Handy already ships.
 */
export type Theme = "system" | "light" | "dark"
/**
 * This Mac's chip and memory, and what should run on it.
 */
export type ThisMac = { chip: string; memory_gb: number; 
/**
 * Speech-to-text runs well on this Mac.
 */
local_speech: boolean; 
/**
 * The local cleanup model (a few GB more) runs well too.
 */
local_cleanup: boolean }
/**
 * What a finished track holds.
 */
export type TrackSummary = { file: string; source: string; seconds: number; 
/**
 * Loudest sample in dBFS; very low means the track is silent (for the
 * system track, usually a missing permission).
 */
peak_dbfs: number; 
/**
 * Seconds of silence added to keep the track on the clock.
 */
padded_seconds: number }
export type TranscribeAcceleratorSetting = "auto" | "cpu" | "gpu"
/**
 * How far the running background work has got.
 */
export type TranscribeProgress = { id: string; stage: Stage; done: number; total: number }
export type TranscriptStatus = "queued" | "transcribing" | "done" | "failed"
export type TypingTool = "auto" | "wtype" | "kwtype" | "dotool" | "ydotool" | "xdotool"
export type VadBackend = "silero" | "earshot"
/**
 * A spoken phrase that, said at the very end of a dictation, is removed from
 * the text and replaced by a key press after the paste.
 */
export type VoiceTrigger = { phrase: string; key: AutoSubmitKey }
export type WindowsMicrophonePermissionStatus = { supported: boolean; overall_access: PermissionAccess; device_access: PermissionAccess; app_access: PermissionAccess; desktop_app_access: PermissionAccess }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
